name: Deploy Hugo to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: ğŸ“¦ Install Node.js Dependencies
        run: npm install

      - name: ğŸ”“ Fix postcss permission
        run: chmod +x ./node_modules/.bin/postcss
        
      - name: ğŸ§± Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.125.6"
          extended: true

      - name: ğŸ”¨ Build Hugo Site
        run: hugo --minify


      - name: ğŸš€ Deploy to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 202.10.47.11
          username: root
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          source: "public/*"
          target: "/home/ajiekusumadhany/public_html/coba-blog/"
          strip_components: 1
